# Site settings
title: Cyber Defenders
email: cyberdefendersprogram@gmail.com
baseurl: "/"
description: ""
url: "https://www.cyberdefendersprogram.com"
blog: "https://www.medium.com/cyberdefenders"
gitrepo: "https://github.com/cyberdefenders"
shenzibanzaiGitrepo: "https://github.com/cyberdefenders/shenzi-banzai"
secrepoGitrepo: "https://github.com/cyberdefenders/secrepo"
redteamMedium: "https://medium.com/cyberdefenders/red-team-rocks-the-house-d197a9b14540"
marchHackathon: "https://medium.com/cyberdefenders/our-march-hackathon-in-2-minutes-a64875d37c58"
summerProgram: "https://medium.com/cyberdefenders/2018-summer-cohort-overview-fb7bc487563a"
medium: "https://medium.com/cyberdefenders"
linkedIn: "https://www.linkedin.com/company/cyberdefenders-program/"
twitter: "https://twitter.com/programcyber?lang=en"
facebook: "https://www.facebook.com/thecyberdefendersprogram/"
bootcamp: "https://medium.com/polyswarm/your-cybersecurity-career-a-training-model-to-get-started-c1cbab40b1bb"


# Build settings
markdown: kramdown
permalink: pretty
