# Site settings
title: Cyber Defenders
email: cyberdefendersprogram@gmail.com
description: ""
blog: "https://www.medium.com/cyberdefenders"
gitrepo: "https://github.com/cyberdefenders"
shenzibanzaigitrepo: "https://github.com/cyberdefenders/shenzi-banzai"
secrepogitrepo: "https://github.com/cyberdefenders/secrepo"
baseurl: "/"
url: "https://www.cyberdefendersprogram.com"

# Build settings
markdown: kramdown
permalink: pretty