# Site settings
title: Cyber Defenders
email: cyberdefendersprogram@gmail.com
url: "https://www.cyberdefendersprogram.com/"
baseurl: "/"
description: "Cyber Defenders Program Homepage"
blog: "https://www.medium.com/cyberdefenders"
gitrepo: "https://github.com/cyberdefenders"
shenzibanzaiGitrepo: "https://github.com/cyberdefenders/shenzi-banzai"
secrepoGitrepo: "https://github.com/cyberdefenders/secrepo"
redteamMedium: "https://medium.com/cyberdefenders/red-team-rocks-the-house-d197a9b14540"
marchHackathon: "https://medium.com/cyberdefenders/our-march-hackathon-in-2-minutes-a64875d37c58"
medium: "https://medium.com/cyberdefenders"
spectrum: "https://spectrum.chat/cyberdefenders"
slack: "https://cyberdefenderstalk.slack.com"
linkedIn: "https://www.linkedin.com/company/cyberdefenders-program/"
twitter: "https://twitter.com/programcyber"
facebook: "https://www.facebook.com/thecyberdefendersprogram/"
instagram: "https://www.instagram.com/cyberdefendersprogram/"
merritthackapp: "https://docs.google.com/forms/d/e/1FAIpQLSeS0RISc0n2GfI_FA6rBJqiLA-VSG2-PCGNcp1BBH4FNPwJSA/viewform"

collections:
  workshops:
    output: true
    permalink: /:collection/:slug

# Build settings
markdown: kramdown
permalink: pretty
exclude:
 - package.json
