# Site settings
title: Cyber Defenders
email: cyberdefendersprogram@gmail.com
description:
blog: https://www.medium.com/cyberdefenders
baseurl: "/"
url: "https://www.cyberdefendersprogram.com"

# Build settings
markdown: kramdown
permalink: pretty
